// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PpeManager.Infrastructure;

#nullable disable

namespace PpeManager.Infrastructure.Migrations
{
    [DbContext(typeof(PpeManagerContext))]
    [Migration("20220104121346_companyMigration")]
    partial class companyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("companyseq", "ppemanager")
                .IncrementsBy(10);

            modelBuilder.HasSequence("ppeCertificationseq", "ppemanager")
                .IncrementsBy(10);

            modelBuilder.HasSequence("ppeseq", "ppemanager")
                .IncrementsBy(10);

            modelBuilder.Entity("PpeManager.Domain.AggregatesModel.AggregateCompany.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "companyseq", "ppemanager");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("companies", "ppemanager");
                });

            modelBuilder.Entity("PpeManager.Domain.AggregatesModel.AggregatePpe.Ppe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "ppeseq", "ppemanager");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ppes", "ppemanager");
                });

            modelBuilder.Entity("PpeManager.Domain.AggregatesModel.AggregatePpe.PpeCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "ppeCertificationseq", "ppemanager");

                    b.Property<string>("ApprovalCertificateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Durability")
                        .HasColumnType("integer");

                    b.Property<int>("PpeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Validity")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PpeId");

                    b.ToTable("ppeCertifications", "ppemanager");
                });

            modelBuilder.Entity("PpeManager.Domain.AggregatesModel.AggregatePpe.PpeCertification", b =>
                {
                    b.HasOne("PpeManager.Domain.AggregatesModel.AggregatePpe.Ppe", "Ppe")
                        .WithMany("PpeCertifications")
                        .HasForeignKey("PpeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ppe");
                });

            modelBuilder.Entity("PpeManager.Domain.AggregatesModel.AggregatePpe.Ppe", b =>
                {
                    b.Navigation("PpeCertifications");
                });
#pragma warning restore 612, 618
        }
    }
}
