global using Flunt.Notifications;
global using Flunt.Validations;
global using MediatR;
global using PpeManager.Domain.AggregatesModel.AggregateCompany;
global using PpeManager.Domain.AggregatesModel.AggregatePpe;
global using PpeManager.Domain.Seedwork;
global using PpeManager.Domain.ValueTypes;
global using System.Reflection;
global using System.Text.RegularExpressions;
